import spacy
from spacy.tokens import DocBin, Span
import os

def merge_pseudo_labels(baseline_model_path, synthetic_input_path, output_path):
    if not os.path.exists(baseline_model_path):
        print(f"[ERROR] Baseline model path not found: {baseline_model_path}")
        return

    print(f"Loading best baseline human model from: {baseline_model_path}")
    nlp = spacy.load(baseline_model_path)
    
    print(f"Reading pristine synthetic documents using model vocabulary...")
    doc_bin_in = DocBin().from_disk(synthetic_input_path)
    # CRUCIAL FIX: Use nlp.vocab instead of spacy.blank("en").vocab
    raw_docs = list(doc_bin_in.get_docs(nlp.vocab))
    
    processed_doc_bin = DocBin()
    added_labels_count = 0
    original_labels_count = 0
    
    print("Beginning knowledge distillation scan...")
    for doc in raw_docs:
        # 1. Store the gold minority label generated by Qwen
        gold_spans = list(doc.spans.get("sc", []))
        original_labels_count += len(gold_spans)
        
        # Create gold boundary map to avoid overlapping collisions
        gold_boundaries = set()
        for span in gold_spans:
            for token_idx in range(span.start, span.end):
                gold_boundaries.add(token_idx)
        
        # 2. Run the baseline model over the raw text to predict missing background classes
        predicted_doc = nlp(doc.text)
        predicted_spans = predicted_doc.spans.get("sc", [])
        
        # 3. Merge non-conflicting background annotations
        merged_spans = gold_spans.copy()
        for p_span in predicted_spans:
            # Check if this predicted token span overlaps with any part of our gold label
            span_tokens = set(range(p_span.start, p_span.end))
            if not span_tokens.intersection(gold_boundaries):
                # CRUCIAL FIX: Use p_span.label_ (string text) instead of p_span.label (integer hash)
                new_span = Span(doc, p_span.start, p_span.end, label=p_span.label_)
                merged_spans.append(new_span)
                added_labels_count += 1
                # Update boundaries to prevent self-collisions within predictions
                for idx in span_tokens:
                    gold_boundaries.add(idx)
                    
        # Assign updated dense span array back to the document
        doc.spans["sc"] = merged_spans
        processed_doc_bin.add(doc)
        
    print(f"\nDistillation Complete!")
    print(f"-> Preserved Gold Labels from Qwen: {original_labels_count}")
    print(f"-> Recovered Pseudo-Labels (Missing background classes): {added_labels_count}")
    
    processed_doc_bin.to_disk(output_path)
    print(f"[SUCCESS] Dense synthetic training data saved to: {output_path}")

if __name__ == "__main__":
    # Point this to whichever baseline fold directory achieved your highest overall performance
    BEST_BASELINE_FOLD = "models/fold1_baseline/model-best" 
    SYNTHETIC_DATA = "data/synthetic_balanced.spacy"
    OUTPUT_DATA = "data/synthetic_pseudo_labeled.spacy"
    
    merge_pseudo_labels(BEST_BASELINE_FOLD, SYNTHETIC_DATA, OUTPUT_DATA)
