import spacy
from spacy.tokens import DocBin, Span
import os

# Minimum confidence score required for a pseudo-label to be accepted.
# Spans predicted below this threshold are discarded as unreliable.
# 0.7 is a conventional starting point in the pseudo-labelling literature:
# it balances label reliability against retaining sufficient augmentation volume.
CONFIDENCE_THRESHOLD = 0.7

# Merge gold synthetic labels with pseudo-labels predicted by a trained baseline model.
# The goal is to densify the training data by preserving trusted synthetic labels
# while filling in missing background entity classes predicted by the model.
def merge_pseudo_labels(baseline_model_path, synthetic_input_path, output_path):

    # Verify the baseline model exists before attempting to load it
    if not os.path.exists(baseline_model_path):
        print(f"[ERROR] Baseline model path not found: {baseline_model_path}")
        return

    # Load the trained baseline spaCy model
    print(f"Loading best baseline human model from: {baseline_model_path}")
    nlp = spacy.load(baseline_model_path)
    
    # Read the synthetic dataset using the model's vocabulary
    # to ensure labels and hashes are interpreted correctly
    print(f"Reading pristine synthetic documents using model vocabulary...")
    doc_bin_in = DocBin().from_disk(synthetic_input_path)

    # CRUCIAL FIX:
    # Use nlp.vocab instead of a fresh blank vocabulary.
    # This preserves label mappings and avoids hash mismatches.
    raw_docs = list(doc_bin_in.get_docs(nlp.vocab))
    
    # Container for the newly merged dataset
    processed_doc_bin = DocBin()

    # Statistics for reporting
    added_labels_count = 0
    original_labels_count = 0
    
    print("Beginning knowledge distillation scan...")

    # Process each synthetic document individually
    for doc in raw_docs:
        # STEP 1: Preserve the original synthetic (gold) annotations

        # Gold spans generated by Qwen or another synthetic-data generator
        gold_spans = list(doc.spans.get("sc", []))

        # Track how many trusted labels existed originally
        original_labels_count += len(gold_spans)
        
        # Build a token-level occupancy map so we can prevent overlap
        # between gold labels and future pseudo-labels
        gold_boundaries = set()

        for span in gold_spans:
            for token_idx in range(span.start, span.end):
                gold_boundaries.add(token_idx)
        
        # STEP 2: Run the baseline model to predict additional spans
        # Re-run inference on the raw document text
        predicted_doc = nlp(doc.text)

        # Retrieve predicted spancat annotations and their confidence scores
        predicted_spans = predicted_doc.spans.get("sc", [])
        span_scores = predicted_doc.spans["sc"].attrs.get("scores", [])
        
        # STEP 3: Merge only non-conflicting, HIGH-CONFIDENCE predictions
        merged_spans = gold_spans.copy()
        CONFIDENCE_THRESHOLD = 0.7

        # Ensure scores are available to avoid zip errors
        if len(predicted_spans) == len(span_scores):
            for p_span, score in zip(predicted_spans, span_scores):
                
                # Check confidence threshold first
                if score >= CONFIDENCE_THRESHOLD:
                    span_tokens = set(range(p_span.start, p_span.end))

                    # Only add predictions that do not overlap with existing gold annotations
                    if not span_tokens.intersection(gold_boundaries):
                        new_span = Span(
                            doc,
                            p_span.start,
                            p_span.end,
                            label=p_span.label_
                        )

                        merged_spans.append(new_span)
                        added_labels_count += 1

                        # Update occupancy map
                        for idx in span_tokens:
                            gold_boundaries.add(idx)
        else:
            print("[WARNING] Span scores not found. Ensure the spancat component saves scores.")
                    
        # Store the final merged span collection
        doc.spans["sc"] = merged_spans

        # Add the updated document to the output dataset
        processed_doc_bin.add(doc)
        
    # Final reporting

    print(f"\nDistillation Complete!")
    print(f"-> Preserved Gold Labels from Qwen: {original_labels_count}")
    print(f"-> Recovered Pseudo-Labels (Missing background classes): {added_labels_count}")
    
    # Save the densified dataset to disk
    processed_doc_bin.to_disk(output_path)

    print(f"[SUCCESS] Dense synthetic training data saved to: {output_path}")

if __name__ == "__main__":

    # Point this to whichever baseline fold directory
    # achieved the strongest validation performance
    BEST_BASELINE_FOLD = "models/roberta_large_teacher/model-best"

    # Input synthetic dataset containing only gold synthetic labels
    SYNTHETIC_DATA = "data/synthetic_zero_shot.spacy"

    # Output dataset containing gold labels + pseudo-labels
    OUTPUT_DATA = "data/synthetic_pseudo_labeled_zero_shot.spacy"
    
    # Run the merge pipeline
    merge_pseudo_labels(BEST_BASELINE_FOLD, SYNTHETIC_DATA, OUTPUT_DATA)
