import argparse
import mlx_lm
import json
import random
import re
import os

# How many sentences to generate for data augmentation
TARGET_CLASSES = {
    "ENDOPHORIC": 2000,
    "JUSTIFYING": 2000,
    "SOURCES":    2000,
    "CITATION":   2000
}

# A list of 11 academic domains. generator randomly picks one per prompt to esnure domain diversity in the syntethic data. 
DOMAINS = [
    "Computer Science", "Sociology", "Molecular Biology", "History",
    "Macroeconomics", "Linguistics", "Quantum Physics", "Cognitive Psychology",
    "Philosophy of Mind", "Clinical Medicine", "Environmental Science"
]

# Category-specific trigger phrases, associated with each engagement marker class. each prompt instructs the model to use one
# of these triggers, making the marker explicit and locatable in the generated sentence.
SEED_TRIGGERS = {
    "ENDOPHORIC": ["in Table", "as shown in", "above", "the following", "as described"],
    "SOURCES": ["researchers", "scholars", "previous studies"],
    "JUSTIFYING": ["because", "therefore", "thus", "since"],  
    "CITATION": ["as noted in", "as argued by", "as shown by", "as demonstrated in"]
}

#taken directly from engagement-annotation-project github (EDT)
GOLD_EXAMPLES = {
    "ENDOPHORIC": "As Table 3 shows, vocabulary size and depth were significantly correlated. | Table 3",
    "SOURCES": "Previous studies showed this effect consistently. | Previous studies",
    "JUSTIFYING": "These methods were selected because they offer greater precision. | because",
    "CITATION": " Some predictions made by Robertson et al (1999) make this even clearer. | Robertson et al (1999)"
}


# Takes a category, domain, trigger phrase, returns a fully formatted prompt string.
# Negative constraints that tells the model what to avoid.
def build_prompt(category: str, domain: str, trigger: str) -> str:
    negative_constraints = (
        "CRITICAL RULE: Do NOT include parenthetical citations (e.g., Smith, 2021), "
        "modal verbs of probability (might, may, could), negations (not, never), or "
        "explicit authorial pronouns (I believe, we contend) UNLESS they are specifically "
        "part of the requested marker.\n"
    )
    # A random integer injected into the prompt text. Adds noise to the prompt text itseld, 
    # nudging the model to produce.
    # different output across calls (to fight against repetitive generation).
    variation_seed = random.randint(10000, 99999)
    # Zero-shot Prompt: To adopt an academic persona for a specific domain; 
    # generate exactly 5 sentences, use the trigger phrase,
    # vary marker position and sentence length; and output in a strict sentence | span format. 
    return (
        f"You are an expert academic writer in the field of {domain}.\n"
        f"Write exactly 5 distinct academic sentences where the phrase \"{trigger}\" "
        f"functions specifically as a {category} engagement marker.\n\n"
        f"IMPORTANT: The phrase \"{trigger}\" must function as {category} in context, "
        f"NOT as any other engagement type. For example:\n"
        f"- If category is JUSTIFYING, '{trigger}' must establish a causal justification, "
        f"not a counter-expectation.\n"
        f"- If category is ENDOPHORIC, '{trigger}' must refer to content within the same "
        f"text, not to an external source.\n"
        f"- If category is SOURCES, '{trigger}' must reference a vague group of researchers "
        f"or scholars, not a specific named author.\n"
        f"- If category is CITATION, '{trigger}' must reference a specific named external "
        f"source, not a vague group.\n\n"
        f"Variation Seed: {variation_seed}\n\n"
        f"{negative_constraints}\n"
        f"DIVERSITY RULES:\n"
        f"- Vary sentence length.\n"
        f"- Place the marker at different positions (beginning, middle, end).\n"
        f"- Each sentence must be on its own line in this exact format:\n"
        f"  <sentence> | <marker span>\n\n"
        f"EXAMPLE OF GOLD STANDARD FORMATTING:\n"
        f"{GOLD_EXAMPLES[category]}\n\n"
        f"NOW GENERATE 5 NEW SENTENCES:\n"
)

# 1. Takes the raw text generated by the LLM
# 2. Parses each generated sentence
# 3. Validates whether the annotation is usable
# 4. Removes duplicates
# 5. Extracts the exact engagement marker span
# 6. Returns only clean training examples

def parse_response_and_validate(response: str, category: str, seen: set) -> list:
    results = [] # creates likst to store all valid parsed examples
    for line in response.split('\n'): # split the model response into individual lines. 
        # Sentence A | Marker becomes
        # [
        # Sentence A | Marker        
        #]
        line = line.strip() # Removes whitespace from the beginning and end, # from " hello " to "hello"
        if '|' not in line: continue # requires the required format, if not skip it
        parts = line.split('|', 1) # split the line into two pars, 1. sentences and 2. marker span
        if len(parts) < 2: continue # checks the format, if not the same, skip it.
        sentence = parts[0].strip() # extracts the the sentence and annotated marker. 
        marker = parts[1].strip()
        sentence = re.sub(r'^[\d\.\-\)\s]+', '', sentence).strip() # cleans numbering 
        # artifacts from LLM outputs
        if not sentence or not marker: continue # rejects empty data
        
        key = sentence.lower().strip() # normalize duplicate detection, capitalization differences
        # do not bypass deduplication. 
        if key in seen: continue # skips duplicates, to prevent from dataset being repititive

        # Search Marker inside the Sentence
        # re.escape(marker) escapers special regex characters safely. e.g. "(1999)"
        # re.ignorecase finds the exact location (the marker)
        match = re.search(re.escape(marker), sentence, re.IGNORECASE)
        matches_count = len(re.findall(re.escape(marker), sentence, re.IGNORECASE))
        
        if match and matches_count == 1: #only accept sentences if the marker exists and it appears once only
            seen.add(key) #stores sentence in the deduplication set
            exact_span = match.group(0) #extracts the exact matched text from the sentence
            results.append({"text": sentence, "label": category, "span": exact_span})
    return results

def main():
    parser = argparse.ArgumentParser() # Creates command-line argument parser
    # define command-line option
    parser.add_argument("--output", type=str, default="data/synthetic_data_clean.jsonl", help="Output JSONL file")
    args = parser.parse_args() # reads terminal arguments
    output_path = args.output # stores output filename

    print("Loading MLX model for synthetic data generation...")
    model_id = "mlx-community/Qwen2.5-32B-Instruct-4bit"
    model, tokenizer = mlx_lm.load(model_id)
    print("Model loaded.\n")

    print(f"Starting generation. Saving directly to {output_path}...\n")
    seen_sentences = set() # duplication tracker
    all_valid_entries = [] # stores every accepted example

    for category, target_count in TARGET_CLASSES.items(): # loops through each engagement category
        print(f"Generating sentences for {category} (Target: {target_count})...")
        collected_count = 0
        triggers = SEED_TRIGGERS[category]
        attempts = 0
        consecutive_zeros = 0
        max_attempts = target_count * 2
        
        with open(output_path, 'a', encoding='utf-8') as f:
            while collected_count < target_count and attempts < max_attempts:
                domain = random.choice(DOMAINS)
                trigger = random.choice(triggers)
                prompt = build_prompt(category, domain, trigger)
                messages = [{"role": "user", "content": prompt}]
                formatted = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

                try:
                    response = mlx_lm.generate(model, tokenizer, prompt=formatted, max_tokens=1024, verbose=False)
                    parsed = parse_response_and_validate(response, category, seen_sentences)
                    
                    if len(parsed) == 0:
                        consecutive_zeros += 1
                    else:
                        consecutive_zeros = 0 
                        
                    for entry in parsed:
                        if collected_count < target_count:
                            f.write(json.dumps(entry, ensure_ascii=False) + '\n')
                            f.flush() 
                            collected_count += 1
                            all_valid_entries.append(entry) # Save for final count
                            
                    attempts += 1
                    if consecutive_zeros >= 50:
                        print(f"  [WARNING] Stuck! 50 consecutive failed attempts. Breaking early.")
                        break
                    if attempts % 5 == 0:
                        print(f"  [{category}] {collected_count}/{target_count} collected (Attempt {attempts})...")
                except Exception as e:
                    print(f"Generation error: {e}")
        print(f"  -> Final count for {category}: {collected_count}\n")

    print(f"\n[SUCCESS] Clean synthetic data saved to {output_path}")
    from collections import Counter
    counts = Counter(e["label"] for e in all_valid_entries)
    print("Final Breakdown:")
    for label, count in sorted(counts.items()):
        print(f"  {label:15s}: {count}")

if __name__ == "__main__":
    main()
