model: "Qwen/Qwen2.5-32B-Instruct"
train: true
data: "data"
seed: 42

num_layers: 64   

lora_parameters:
  keys: [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "gate_proj",
    "up_proj",
    "down_proj"
  ]
  rank: 16
  scale: 2.0
  dropout: 0.05

batch_size: 8
iters: 3500
learning_rate: 2e-5
steps_per_eval: 100
save_every: 500
adapter_path: "adapters"
